#!/usr/bin/env bash

set -eu -o pipefail

go mod tidy -compat=1.20
go mod vendor

DIFF_PATHS="go.mod go.sum vendor/"
DIFF=$(git status --porcelain -- ${DIFF_PATHS})

if [ "$DIFF" ]; then
    echo
    echo "These files were modified:"
    echo
    echo "$DIFF"
    echo
    exit 1
else
    echo "$DIFF_PATHS are correct"
fi
